title: David Vaughn's Portfolio
description: Software Engineer & Developer Portfolio
remote_theme: cotes2020/jekyll-theme-chirpy

# Theme settings
theme_mode: dark  # [light|dark]
avatar: "/assets/img/avatar.jpg"
toc: true

# Site settings
author:
  name: David Vaughn
  email: vaughnd544@gmail.com
  github: David-Vaughn4

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  
# Custom settings
show_downloads: true
google_analytics: # Add your Google Analytics tracking ID here

# Navigation
header_pages:
  - about.md
  - projects.md
  - contact.md

# Social links
social:
  github: David-Vaughn4
  linkedin: # Add your LinkedIn username
  twitter: # Add your Twitter handle

# Chirpy theme settings
timezone: America/New_York

# The sidebar items
sidebar:
  avatar: true
  subtitle: "Software Engineer & Developer"
  priority:
    Home: 1
    Projects: 2
    About: 3
    Contact: 4

# Site features
comments: false
math: true  # for displaying mathematical equations
mermaid: true  # for creating diagrams
img_cdn: ''  # for faster image loading if you have a CDN

# Useful metadata
github:
  username: David-Vaughn4
social:
  name: David Vaughn
  email: vaughnd544@gmail.com
  links:
    - https://github.com/David-Vaughn4
  github: David-Vaughn4
  email: vaughnd544@gmail.com

# Excerpt word length
excerpt_length: 50

# Cover image for social sharing
share-img: "Images/cover-image.jpg"

# Add a subtitle to your website
subtitle: "Building Digital Solutions"
