title: David Vaughn's Portfolio
description: Software Engineer & Developer Portfolio
remote_theme: daattali/beautiful-jekyll

# Site settings
author:
  name: David Vaughn
  email: vaughnd544@gmail.com
  github: David-Vaughn4

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  
# Custom settings
show_downloads: true
google_analytics: # Add your Google Analytics tracking ID here

# Navigation
header_pages:
  - about.md
  - projects.md
  - contact.md

# Social links
social:
  github: David-Vaughn4
  linkedin: # Add your LinkedIn username
  twitter: # Add your Twitter handle

# Theme customization - Beautiful Jekyll specific
navbar-col: "#123456"
navbar-text-col: "#FFFFFF"
navbar-border-col: "#234567"
page-col: "#1a1a1a"
text-col: "#FFFFFF"
link-col: "#4FB1BA"
hover-col: "#25CCDB"
footer-col: "#123456"
footer-text-col: "#FFFFFF"
footer-link-col: "#4FB1BA"

# Additional Beautiful Jekyll settings
title-separator: "|"
round-avatar: true
social-network-links:
  github: David-Vaughn4
  email: vaughnd544@gmail.com

# Excerpt word length
excerpt_length: 50

# Cover image for social sharing
share-img: "Images/cover-image.jpg"

# Add a subtitle to your website
subtitle: "Building Digital Solutions"
